name: 'Run Unit Tests'

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  TURBO_TELEMETRY_DISABLED: 1

permissions:
  contents: read
  actions: read
  checks: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 23
                cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install

            - name: Run Tests
              run: pnpm turbo test

            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                name: Vitest Reports
                path: "reports/vitest-*.xml"
                reporter: jest-junit
                token: ${{ github.token }}
